# Generated by Django 5.0.3 on 2024-03-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('code', models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='codigo')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('description', models.TextField(verbose_name='descripcion')),
                ('credits', models.IntegerField(verbose_name='creditos')),
                ('Creation_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('update_date', models.DateField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'Materias',
            },
        ),
    ]
