# Generated by Django 5.0.3 on 2024-03-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0005_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Profesores'},
        ),
        migrations.AddField(
            model_name='students',
            name='date_of_birth',
            field=models.DateField(default=None, null=True, verbose_name='fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='students',
            name='photo',
            field=models.ImageField(default='null', upload_to='', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(default='null', upload_to='', verbose_name='foto'),
        ),
    ]
