# Generated by Django 5.0.3 on 2024-03-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_alter_teacher_options_students_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='date_of_birth',
            field=models.DateField(default=None, verbose_name='fecha de nacimiento'),
        ),
    ]
