# Generated by Django 5.0.3 on 2024-03-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0007_alter_students_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento'),
        ),
    ]
