# Generated by Django 5.0.3 on 2024-04-06 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0008_alter_students_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careers',
            options={'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterModelOptions(
            name='materi',
            options={'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
        migrations.AddField(
            model_name='students',
            name='careers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.careers'),
        ),
        migrations.AlterField(
            model_name='students',
            name='photo',
            field=models.ImageField(default='null', upload_to='Estudiantes', verbose_name='foto'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(default='null', upload_to='Maestros', verbose_name='foto'),
        ),
    ]
