# Generated by Django 5.0.3 on 2024-04-06 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0009_alter_careers_options_alter_materi_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='materi',
            field=models.ManyToManyField(blank=True, null=True, to='pagina.materi', verbose_name='materia'),
        ),
        migrations.AlterField(
            model_name='students',
            name='careers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.careers', verbose_name='carrera'),
        ),
    ]
