# Generated by Django 5.0.3 on 2024-04-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0010_teacher_materi_alter_students_careers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='materi',
            field=models.ManyToManyField(to='pagina.materi', verbose_name='materia'),
        ),
    ]
