# Generated by Django 5.0.3 on 2024-04-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0012_careers_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='materi',
        ),
    ]
