# Generated by Django 5.0.3 on 2024-04-09 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0013_remove_teacher_materi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_Materi',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False, verbose_name='codigo')),
                ('materi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.materi', verbose_name='materia')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.teacher', verbose_name='maestro')),
            ],
            options={
                'verbose_name': 'Maestro y Materia',
                'verbose_name_plural': 'Maestros y Materias',
            },
        ),
    ]
