# Generated by Django 5.0.3 on 2024-04-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0014_teacher_materi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='careers',
            options={'ordering': ['code'], 'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterModelOptions(
            name='materi',
            options={'ordering': ['code'], 'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['code'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['code'], 'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
    ]
