# Generated by Django 5.0.3 on 2024-04-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0014_teacher_materi'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='materi',
            field=models.ManyToManyField(to='pagina.materi', verbose_name='materia'),
        ),
        migrations.DeleteModel(
            name='Teacher_Materi',
        ),
    ]
